version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    container_name: bts-db
    env_file:
      - ./.env
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - db:/data/db
    networks:
      - mynetwork

  app:
    depends_on:
      - mongo
    build: .
    restart: always
    env_file:
      - ./.env
    ports:
      - 4000:4000
    environment:
      - DB_HOST=mongodb
      - DB_USER=${MONGODB_USER}
      - DB_PASSWORD=${MONGODB_PASSWORD}
      - DB_NAME=${MONGODB_NAME}
      - DB_PORT=27017
      - MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@bts-db:27017/${MONGODB_NAME}?authSource=admin
    stdin_open: true
    tty: true
    networks:
      - mynetwork
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongo:27017/
    networks:
      - mynetwork

volumes:
  db:

networks:
  mynetwork:
    driver: bridge
